# Lesli
#
# Copyright (c) 2023, Lesli Technologies, S. A.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# ProjectRaven - Backend platform for apps, websites and IoT devices
#
# Powered by https://www.lesli.tech
# Building a better future, one line of code at a time.
#
# @contact  <hello@lesli.tech>
# @website  <https://lesli.tech>
# @license  GPLv3 http://www.gnu.org/licenses/gpl-3.0.en.html

# // · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
# // · 



# Specs for Lesli Core
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
name: "DatenBanken specs workflow"
on:


  # execute this workflow only when trying to merge from dev branch to master
  pull_request:
    branches: [master, production]

  push:
    branches: [master]

  # Allow to execute this test manually from the Github web app
  workflow_dispatch:

jobs:
  test:
    name: Test workflow for DatenBaneken Server
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [5.0]

    steps:

      # Clone the current repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Use the official receipt to install node in ubuntu
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'


      # Start mongodb
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}


      # install packages
      - run: npm ci
      
      
      - run: cp ./config/environment.js ./config/test.js


      # Run tests
      - name: "Run specs"
        run: npm test
